column table_name        FORMAT a20 heading 'Table Name'
column segment      format a30 heading 'Segment Name'
column lob_column        format a20 heading 'LOB Column'
column status            format a20  heading 'Status'
column size_gb           format 9999.99 heading 'Size in GB'
set echo off verify off
SELECT SEGMENT_NAME TABLE_NAME, '1.Table' type, '-' SEGMENT, TABLESPACE_NAME, '-' LOB_COLUMN, '-' status, ROUND(SUM(BYTES)/1024/1024/1024,2) SIZE_GB  FROM DBA_SEGMENTS
WHERE SEGMENT_NAME IN ('&1')
GROUP BY SEGMENT_NAME, TABLESPACE_NAME
UNION ALL
SELECT B.TABLE_NAME, '2.Lob' type, A.SEGMENT_NAME, A.TABLESPACE_NAME, B.COLUMN_NAME, '-' status, ROUND(SUM(BYTES)/1024/1024/1024,2) FROM DBA_SEGMENTS A, DBA_LOBS B
WHERE
   a.segment_name = B.SEGMENT_NAME  AND
   (A.SEGMENT_NAME IN (SELECT SEGMENT_NAME FROM DBA_LOBS WHERE TABLE_NAME IN ('&1')) )
GROUP BY B.TABLE_NAME, A.SEGMENT_NAME, A.TABLESPACE_NAME, B.COLUMN_NAME
UNION ALL
SELECT B.TABLE_NAME, '3.Lob Index' type, A.SEGMENT_NAME, A.TABLESPACE_NAME, B.COLUMN_NAME, c.status, ROUND(SUM(BYTES)/1024/1024/1024,2) FROM DBA_SEGMENTS A, DBA_LOBS B, dba_indexes c
WHERE
   a.segment_name = c.index_name and
   a.segment_name = B.INDEX_NAME  AND
   A.SEGMENT_NAME IN (SELECT INDEX_NAME FROM DBA_LOBS WHERE TABLE_NAME  IN ('&1'))
GROUP BY B.TABLE_NAME, A.SEGMENT_NAME, A.TABLESPACE_NAME, B.COLUMN_NAME, c.status
UNION ALL
SELECT C.TABLE_NAME, '4.Index' type, A.SEGMENT_NAME, A.TABLESPACE_NAME, '-', c.status, ROUND(SUM(BYTES)/1024/1024/1024,2) FROM DBA_SEGMENTS A, dba_indexes c
WHERE SEGMENT_NAME IN (SELECT INDEX_NAME FROM DBA_INDEXES WHERE TABLE_NAME IN ('&1'))
AND SEGMENT_NAME NOT LIKE 'SYS%'
and a.segment_name = c.index_name
GROUP BY C.TABLE_NAME, A.SEGMENT_NAME, A.TABLESPACE_NAME, c.status
ORDER BY TABLE_NAME, type, TABLESPACE_NAME;
